### PR TITLE
fix(build-url): pass optional gateway enpoint when build url

### PR DESCRIPTION
**Pull request by thinhbuihong**
**Description
- I see that the gateway endpoint in production is different from the sandbox so I think it would be better if we could pass the endpoint to it

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [x] Code style update
- [ ] Test
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR related issues or references:**
-

### CODE REVIEW

**Comment by lehuygiang28** [comment]
Nice, but I think we should change the name of this to something like `PAYMENT_ENDPOINT` for greater clarity

**Comment by thinhbuihong** [comment]
> Nice, but I think we should change the name of this to something like `PAYMENT_ENDPOINT` for greater clarity

I think the parameter should not be named upper snake case, so can I rename it `gatewayEndPoint`?

**Comment by lehuygiang28** [comment]
> I think the parameter should not be named upper snake case, so can I rename it `gatewayEndPoint`?

Yeah, sure. I mean, you can change both the new and the old constants from `GATEWAY_ENDPOINT` to `PAYMENT_ENDPOINT`. Do you think `payment` is clearer than `gateway`?

`GATEWAY_ENDPOINT` -> `PAYMENT_ENDPOINT`
`endPoint` -> `paymentEndpoint`

**Comment by thinhbuihong** [comment]
@lehuygiang28 I have renamed the old constant

**Pull request merged**
